name: "PHA Guardian"
version: "0.0.78"
slug: "pha_guardian_dev"
description: "Guardian API monitoring tool"
# Use this for Supervisor access
hassio_api: true
hassio_role: admin
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
# Set to false to use standard Docker routing (safer for API calls)
host_network: false
# Ensure the container knows it's an S6-overlay app
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Guardian API Port"
map:
  - config:rw
  - share:rw
options:
  guardian_ip: "10.0.0.140"
  dev_mode: false
schema:
  guardian_ip: str
  dev_mode: bool
