FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY logging_config.py .
COPY guardian_client.py .
COPY supervisor_client.py .

COPY run.sh .

RUN chmod +x run.sh

CMD ["./run.sh"]